# Simplest
ps_module('A')

# Specific
ps_module('B',src='B.purs')

# Modules
ps_module('C',modules=[':A',':B'])

# Main
ps_module('D',src='Main.purs',modules=':C')

# Src
ps_module('F', src = ['F1.purs','F2.purs'])

# Tests
ps_module('G', tests = 'GTest.purs')

# Additional test
ps_test('GTest2',modules=':G')
